spring:
  application:
    name: HiPerfJavaPersistence
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:mysql://localhost:3306/hi_perf_java_pers
    username: root
    password: 123456
#    hikari:
#      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        connection:
#          provider_disables_autocommit: true
        generate_statistics: true #generate hibernate_* statistics at http://localhost:8080/actuator/prometheus
        session:
          events:
            log: false #disable statistics in log, but leave in actuator
    open-in-view: false #do not let view to lazy init properties from entities
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
