/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.AssigneduuidgeneratorRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Assigneduuidgenerator extends TableImpl<AssigneduuidgeneratorRecord> {

    private static final long serialVersionUID = 198254953;

    /**
     * The reference instance of <code>hi_perf_java_pers.assigneduuidgenerator</code>
     */
    public static final Assigneduuidgenerator ASSIGNEDUUIDGENERATOR = new Assigneduuidgenerator();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AssigneduuidgeneratorRecord> getRecordType() {
        return AssigneduuidgeneratorRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.assigneduuidgenerator.id</code>.
     */
    public final TableField<AssigneduuidgeneratorRecord, byte[]> ID = createField("id", org.jooq.impl.SQLDataType.BINARY(16).nullable(false), this, "");

    /**
     * Create a <code>hi_perf_java_pers.assigneduuidgenerator</code> table reference
     */
    public Assigneduuidgenerator() {
        this(DSL.name("assigneduuidgenerator"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.assigneduuidgenerator</code> table reference
     */
    public Assigneduuidgenerator(String alias) {
        this(DSL.name(alias), ASSIGNEDUUIDGENERATOR);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.assigneduuidgenerator</code> table reference
     */
    public Assigneduuidgenerator(Name alias) {
        this(alias, ASSIGNEDUUIDGENERATOR);
    }

    private Assigneduuidgenerator(Name alias, Table<AssigneduuidgeneratorRecord> aliased) {
        this(alias, aliased, null);
    }

    private Assigneduuidgenerator(Name alias, Table<AssigneduuidgeneratorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Assigneduuidgenerator(Table<O> child, ForeignKey<O, AssigneduuidgeneratorRecord> key) {
        super(child, key, ASSIGNEDUUIDGENERATOR);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ASSIGNEDUUIDGENERATOR_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AssigneduuidgeneratorRecord> getPrimaryKey() {
        return Keys.KEY_ASSIGNEDUUIDGENERATOR_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AssigneduuidgeneratorRecord>> getKeys() {
        return Arrays.<UniqueKey<AssigneduuidgeneratorRecord>>asList(Keys.KEY_ASSIGNEDUUIDGENERATOR_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Assigneduuidgenerator as(String alias) {
        return new Assigneduuidgenerator(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Assigneduuidgenerator as(Name alias) {
        return new Assigneduuidgenerator(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Assigneduuidgenerator rename(String name) {
        return new Assigneduuidgenerator(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Assigneduuidgenerator rename(Name name) {
        return new Assigneduuidgenerator(name, null);
    }
}
