/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.AuthorManyBiRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorManyBi extends TableImpl<AuthorManyBiRecord> {

    private static final long serialVersionUID = -102343917;

    /**
     * The reference instance of <code>hi_perf_java_pers.author_many_bi</code>
     */
    public static final AuthorManyBi AUTHOR_MANY_BI = new AuthorManyBi();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthorManyBiRecord> getRecordType() {
        return AuthorManyBiRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.author_many_bi.id</code>.
     */
    public final TableField<AuthorManyBiRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>hi_perf_java_pers.author_many_bi.name</code>.
     */
    public final TableField<AuthorManyBiRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>hi_perf_java_pers.author_many_bi</code> table reference
     */
    public AuthorManyBi() {
        this(DSL.name("author_many_bi"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.author_many_bi</code> table reference
     */
    public AuthorManyBi(String alias) {
        this(DSL.name(alias), AUTHOR_MANY_BI);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.author_many_bi</code> table reference
     */
    public AuthorManyBi(Name alias) {
        this(alias, AUTHOR_MANY_BI);
    }

    private AuthorManyBi(Name alias, Table<AuthorManyBiRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuthorManyBi(Name alias, Table<AuthorManyBiRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AuthorManyBi(Table<O> child, ForeignKey<O, AuthorManyBiRecord> key) {
        super(child, key, AUTHOR_MANY_BI);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.AUTHOR_MANY_BI_PRIMARY, Indexes.AUTHOR_MANY_BI_UK_81A5W9QC9SSM6XLY74RM34B4A);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AuthorManyBiRecord, Long> getIdentity() {
        return Keys.IDENTITY_AUTHOR_MANY_BI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AuthorManyBiRecord> getPrimaryKey() {
        return Keys.KEY_AUTHOR_MANY_BI_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AuthorManyBiRecord>> getKeys() {
        return Arrays.<UniqueKey<AuthorManyBiRecord>>asList(Keys.KEY_AUTHOR_MANY_BI_PRIMARY, Keys.KEY_AUTHOR_MANY_BI_UK_81A5W9QC9SSM6XLY74RM34B4A);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorManyBi as(String alias) {
        return new AuthorManyBi(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorManyBi as(Name alias) {
        return new AuthorManyBi(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorManyBi rename(String name) {
        return new AuthorManyBi(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorManyBi rename(Name name) {
        return new AuthorManyBi(name, null);
    }
}
