/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.BookManyjRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookManyj extends TableImpl<BookManyjRecord> {

    private static final long serialVersionUID = 1180969647;

    /**
     * The reference instance of <code>hi_perf_java_pers.book_manyj</code>
     */
    public static final BookManyj BOOK_MANYJ = new BookManyj();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookManyjRecord> getRecordType() {
        return BookManyjRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.book_manyj.id</code>.
     */
    public final TableField<BookManyjRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * Create a <code>hi_perf_java_pers.book_manyj</code> table reference
     */
    public BookManyj() {
        this(DSL.name("book_manyj"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.book_manyj</code> table reference
     */
    public BookManyj(String alias) {
        this(DSL.name(alias), BOOK_MANYJ);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.book_manyj</code> table reference
     */
    public BookManyj(Name alias) {
        this(alias, BOOK_MANYJ);
    }

    private BookManyj(Name alias, Table<BookManyjRecord> aliased) {
        this(alias, aliased, null);
    }

    private BookManyj(Name alias, Table<BookManyjRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> BookManyj(Table<O> child, ForeignKey<O, BookManyjRecord> key) {
        super(child, key, BOOK_MANYJ);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BOOK_MANYJ_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BookManyjRecord, Long> getIdentity() {
        return Keys.IDENTITY_BOOK_MANYJ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BookManyjRecord> getPrimaryKey() {
        return Keys.KEY_BOOK_MANYJ_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BookManyjRecord>> getKeys() {
        return Arrays.<UniqueKey<BookManyjRecord>>asList(Keys.KEY_BOOK_MANYJ_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookManyj as(String alias) {
        return new BookManyj(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookManyj as(Name alias) {
        return new BookManyj(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BookManyj rename(String name) {
        return new BookManyj(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BookManyj rename(Name name) {
        return new BookManyj(name, null);
    }
}
