/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.BookManyBiRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookManyBi extends TableImpl<BookManyBiRecord> {

    private static final long serialVersionUID = -557541904;

    /**
     * The reference instance of <code>hi_perf_java_pers.book_many_bi</code>
     */
    public static final BookManyBi BOOK_MANY_BI = new BookManyBi();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookManyBiRecord> getRecordType() {
        return BookManyBiRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.book_many_bi.id</code>.
     */
    public final TableField<BookManyBiRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * Create a <code>hi_perf_java_pers.book_many_bi</code> table reference
     */
    public BookManyBi() {
        this(DSL.name("book_many_bi"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.book_many_bi</code> table reference
     */
    public BookManyBi(String alias) {
        this(DSL.name(alias), BOOK_MANY_BI);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.book_many_bi</code> table reference
     */
    public BookManyBi(Name alias) {
        this(alias, BOOK_MANY_BI);
    }

    private BookManyBi(Name alias, Table<BookManyBiRecord> aliased) {
        this(alias, aliased, null);
    }

    private BookManyBi(Name alias, Table<BookManyBiRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> BookManyBi(Table<O> child, ForeignKey<O, BookManyBiRecord> key) {
        super(child, key, BOOK_MANY_BI);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BOOK_MANY_BI_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BookManyBiRecord, Long> getIdentity() {
        return Keys.IDENTITY_BOOK_MANY_BI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BookManyBiRecord> getPrimaryKey() {
        return Keys.KEY_BOOK_MANY_BI_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BookManyBiRecord>> getKeys() {
        return Arrays.<UniqueKey<BookManyBiRecord>>asList(Keys.KEY_BOOK_MANY_BI_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookManyBi as(String alias) {
        return new BookManyBi(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookManyBi as(Name alias) {
        return new BookManyBi(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BookManyBi rename(String name) {
        return new BookManyBi(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BookManyBi rename(Name name) {
        return new BookManyBi(name, null);
    }
}
