/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.Child2tpcRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Child2tpc extends TableImpl<Child2tpcRecord> {

    private static final long serialVersionUID = 1438069624;

    /**
     * The reference instance of <code>hi_perf_java_pers.child2tpc</code>
     */
    public static final Child2tpc CHILD2TPC = new Child2tpc();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Child2tpcRecord> getRecordType() {
        return Child2tpcRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.child2tpc.id</code>.
     */
    public final TableField<Child2tpcRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>hi_perf_java_pers.child2tpc.name</code>.
     */
    public final TableField<Child2tpcRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>hi_perf_java_pers.child2tpc.child2prop</code>.
     */
    public final TableField<Child2tpcRecord, String> CHILD2PROP = createField("child2prop", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>hi_perf_java_pers.child2tpc</code> table reference
     */
    public Child2tpc() {
        this(DSL.name("child2tpc"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.child2tpc</code> table reference
     */
    public Child2tpc(String alias) {
        this(DSL.name(alias), CHILD2TPC);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.child2tpc</code> table reference
     */
    public Child2tpc(Name alias) {
        this(alias, CHILD2TPC);
    }

    private Child2tpc(Name alias, Table<Child2tpcRecord> aliased) {
        this(alias, aliased, null);
    }

    private Child2tpc(Name alias, Table<Child2tpcRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Child2tpc(Table<O> child, ForeignKey<O, Child2tpcRecord> key) {
        super(child, key, CHILD2TPC);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CHILD2TPC_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Child2tpcRecord> getPrimaryKey() {
        return Keys.KEY_CHILD2TPC_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Child2tpcRecord>> getKeys() {
        return Arrays.<UniqueKey<Child2tpcRecord>>asList(Keys.KEY_CHILD2TPC_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Child2tpc as(String alias) {
        return new Child2tpc(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Child2tpc as(Name alias) {
        return new Child2tpc(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Child2tpc rename(String name) {
        return new Child2tpc(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Child2tpc rename(Name name) {
        return new Child2tpc(name, null);
    }
}
