/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.Child1tpcRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Child1tpc extends TableImpl<Child1tpcRecord> {

    private static final long serialVersionUID = -1745673944;

    /**
     * The reference instance of <code>hi_perf_java_pers.child1tpc</code>
     */
    public static final Child1tpc CHILD1TPC = new Child1tpc();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Child1tpcRecord> getRecordType() {
        return Child1tpcRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.child1tpc.id</code>.
     */
    public final TableField<Child1tpcRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>hi_perf_java_pers.child1tpc.name</code>.
     */
    public final TableField<Child1tpcRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>hi_perf_java_pers.child1tpc.child1prop</code>.
     */
    public final TableField<Child1tpcRecord, String> CHILD1PROP = createField("child1prop", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>hi_perf_java_pers.child1tpc</code> table reference
     */
    public Child1tpc() {
        this(DSL.name("child1tpc"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.child1tpc</code> table reference
     */
    public Child1tpc(String alias) {
        this(DSL.name(alias), CHILD1TPC);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.child1tpc</code> table reference
     */
    public Child1tpc(Name alias) {
        this(alias, CHILD1TPC);
    }

    private Child1tpc(Name alias, Table<Child1tpcRecord> aliased) {
        this(alias, aliased, null);
    }

    private Child1tpc(Name alias, Table<Child1tpcRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Child1tpc(Table<O> child, ForeignKey<O, Child1tpcRecord> key) {
        super(child, key, CHILD1TPC);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CHILD1TPC_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Child1tpcRecord> getPrimaryKey() {
        return Keys.KEY_CHILD1TPC_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Child1tpcRecord>> getKeys() {
        return Arrays.<UniqueKey<Child1tpcRecord>>asList(Keys.KEY_CHILD1TPC_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Child1tpc as(String alias) {
        return new Child1tpc(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Child1tpc as(Name alias) {
        return new Child1tpc(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Child1tpc rename(String name) {
        return new Child1tpc(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Child1tpc rename(Name name) {
        return new Child1tpc(name, null);
    }
}
