/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.Child1msRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Child1ms extends TableImpl<Child1msRecord> {

    private static final long serialVersionUID = 1967731323;

    /**
     * The reference instance of <code>hi_perf_java_pers.child1ms</code>
     */
    public static final Child1ms CHILD1MS = new Child1ms();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Child1msRecord> getRecordType() {
        return Child1msRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.child1ms.id</code>.
     */
    public final TableField<Child1msRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>hi_perf_java_pers.child1ms.name</code>.
     */
    public final TableField<Child1msRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>hi_perf_java_pers.child1ms.child1prop</code>.
     */
    public final TableField<Child1msRecord, String> CHILD1PROP = createField("child1prop", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>hi_perf_java_pers.child1ms</code> table reference
     */
    public Child1ms() {
        this(DSL.name("child1ms"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.child1ms</code> table reference
     */
    public Child1ms(String alias) {
        this(DSL.name(alias), CHILD1MS);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.child1ms</code> table reference
     */
    public Child1ms(Name alias) {
        this(alias, CHILD1MS);
    }

    private Child1ms(Name alias, Table<Child1msRecord> aliased) {
        this(alias, aliased, null);
    }

    private Child1ms(Name alias, Table<Child1msRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Child1ms(Table<O> child, ForeignKey<O, Child1msRecord> key) {
        super(child, key, CHILD1MS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CHILD1MS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Child1msRecord, Long> getIdentity() {
        return Keys.IDENTITY_CHILD1MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Child1msRecord> getPrimaryKey() {
        return Keys.KEY_CHILD1MS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Child1msRecord>> getKeys() {
        return Arrays.<UniqueKey<Child1msRecord>>asList(Keys.KEY_CHILD1MS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Child1ms as(String alias) {
        return new Child1ms(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Child1ms as(Name alias) {
        return new Child1ms(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Child1ms rename(String name) {
        return new Child1ms(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Child1ms rename(Name name) {
        return new Child1ms(name, null);
    }
}
