/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.ParenttpcRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Parenttpc extends TableImpl<ParenttpcRecord> {

    private static final long serialVersionUID = 1219054329;

    /**
     * The reference instance of <code>hi_perf_java_pers.parenttpc</code>
     */
    public static final Parenttpc PARENTTPC = new Parenttpc();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ParenttpcRecord> getRecordType() {
        return ParenttpcRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.parenttpc.id</code>.
     */
    public final TableField<ParenttpcRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>hi_perf_java_pers.parenttpc.name</code>.
     */
    public final TableField<ParenttpcRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>hi_perf_java_pers.parenttpc</code> table reference
     */
    public Parenttpc() {
        this(DSL.name("parenttpc"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.parenttpc</code> table reference
     */
    public Parenttpc(String alias) {
        this(DSL.name(alias), PARENTTPC);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.parenttpc</code> table reference
     */
    public Parenttpc(Name alias) {
        this(alias, PARENTTPC);
    }

    private Parenttpc(Name alias, Table<ParenttpcRecord> aliased) {
        this(alias, aliased, null);
    }

    private Parenttpc(Name alias, Table<ParenttpcRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Parenttpc(Table<O> child, ForeignKey<O, ParenttpcRecord> key) {
        super(child, key, PARENTTPC);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PARENTTPC_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ParenttpcRecord> getPrimaryKey() {
        return Keys.KEY_PARENTTPC_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ParenttpcRecord>> getKeys() {
        return Arrays.<UniqueKey<ParenttpcRecord>>asList(Keys.KEY_PARENTTPC_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Parenttpc as(String alias) {
        return new Parenttpc(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Parenttpc as(Name alias) {
        return new Parenttpc(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Parenttpc rename(String name) {
        return new Parenttpc(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Parenttpc rename(Name name) {
        return new Parenttpc(name, null);
    }
}
