/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.ParentJtRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParentJt extends TableImpl<ParentJtRecord> {

    private static final long serialVersionUID = 534926985;

    /**
     * The reference instance of <code>hi_perf_java_pers.parent_jt</code>
     */
    public static final ParentJt PARENT_JT = new ParentJt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ParentJtRecord> getRecordType() {
        return ParentJtRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.parent_jt.id</code>.
     */
    public final TableField<ParentJtRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>hi_perf_java_pers.parent_jt.name</code>.
     */
    public final TableField<ParentJtRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>hi_perf_java_pers.parent_jt</code> table reference
     */
    public ParentJt() {
        this(DSL.name("parent_jt"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.parent_jt</code> table reference
     */
    public ParentJt(String alias) {
        this(DSL.name(alias), PARENT_JT);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.parent_jt</code> table reference
     */
    public ParentJt(Name alias) {
        this(alias, PARENT_JT);
    }

    private ParentJt(Name alias, Table<ParentJtRecord> aliased) {
        this(alias, aliased, null);
    }

    private ParentJt(Name alias, Table<ParentJtRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ParentJt(Table<O> child, ForeignKey<O, ParentJtRecord> key) {
        super(child, key, PARENT_JT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PARENT_JT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ParentJtRecord, Long> getIdentity() {
        return Keys.IDENTITY_PARENT_JT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ParentJtRecord> getPrimaryKey() {
        return Keys.KEY_PARENT_JT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ParentJtRecord>> getKeys() {
        return Arrays.<UniqueKey<ParentJtRecord>>asList(Keys.KEY_PARENT_JT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParentJt as(String alias) {
        return new ParentJt(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParentJt as(Name alias) {
        return new ParentJt(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ParentJt rename(String name) {
        return new ParentJt(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ParentJt rename(Name name) {
        return new ParentJt(name, null);
    }
}
