/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.PooledSequenceGeneratorRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PooledSequenceGenerator extends TableImpl<PooledSequenceGeneratorRecord> {

    private static final long serialVersionUID = 1884588598;

    /**
     * The reference instance of <code>hi_perf_java_pers.pooled_sequence_generator</code>
     */
    public static final PooledSequenceGenerator POOLED_SEQUENCE_GENERATOR = new PooledSequenceGenerator();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PooledSequenceGeneratorRecord> getRecordType() {
        return PooledSequenceGeneratorRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.pooled_sequence_generator.id</code>.
     */
    public final TableField<PooledSequenceGeneratorRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>hi_perf_java_pers.pooled_sequence_generator</code> table reference
     */
    public PooledSequenceGenerator() {
        this(DSL.name("pooled_sequence_generator"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.pooled_sequence_generator</code> table reference
     */
    public PooledSequenceGenerator(String alias) {
        this(DSL.name(alias), POOLED_SEQUENCE_GENERATOR);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.pooled_sequence_generator</code> table reference
     */
    public PooledSequenceGenerator(Name alias) {
        this(alias, POOLED_SEQUENCE_GENERATOR);
    }

    private PooledSequenceGenerator(Name alias, Table<PooledSequenceGeneratorRecord> aliased) {
        this(alias, aliased, null);
    }

    private PooledSequenceGenerator(Name alias, Table<PooledSequenceGeneratorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PooledSequenceGenerator(Table<O> child, ForeignKey<O, PooledSequenceGeneratorRecord> key) {
        super(child, key, POOLED_SEQUENCE_GENERATOR);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.POOLED_SEQUENCE_GENERATOR_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PooledSequenceGeneratorRecord> getPrimaryKey() {
        return Keys.KEY_POOLED_SEQUENCE_GENERATOR_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PooledSequenceGeneratorRecord>> getKeys() {
        return Arrays.<UniqueKey<PooledSequenceGeneratorRecord>>asList(Keys.KEY_POOLED_SEQUENCE_GENERATOR_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PooledSequenceGenerator as(String alias) {
        return new PooledSequenceGenerator(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PooledSequenceGenerator as(Name alias) {
        return new PooledSequenceGenerator(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PooledSequenceGenerator rename(String name) {
        return new PooledSequenceGenerator(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PooledSequenceGenerator rename(Name name) {
        return new PooledSequenceGenerator(name, null);
    }
}
