/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.PostManyUniRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostManyUni extends TableImpl<PostManyUniRecord> {

    private static final long serialVersionUID = 1955757322;

    /**
     * The reference instance of <code>hi_perf_java_pers.post_many_uni</code>
     */
    public static final PostManyUni POST_MANY_UNI = new PostManyUni();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PostManyUniRecord> getRecordType() {
        return PostManyUniRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.post_many_uni.id</code>.
     */
    public final TableField<PostManyUniRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * Create a <code>hi_perf_java_pers.post_many_uni</code> table reference
     */
    public PostManyUni() {
        this(DSL.name("post_many_uni"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.post_many_uni</code> table reference
     */
    public PostManyUni(String alias) {
        this(DSL.name(alias), POST_MANY_UNI);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.post_many_uni</code> table reference
     */
    public PostManyUni(Name alias) {
        this(alias, POST_MANY_UNI);
    }

    private PostManyUni(Name alias, Table<PostManyUniRecord> aliased) {
        this(alias, aliased, null);
    }

    private PostManyUni(Name alias, Table<PostManyUniRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PostManyUni(Table<O> child, ForeignKey<O, PostManyUniRecord> key) {
        super(child, key, POST_MANY_UNI);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.POST_MANY_UNI_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PostManyUniRecord, Long> getIdentity() {
        return Keys.IDENTITY_POST_MANY_UNI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PostManyUniRecord> getPrimaryKey() {
        return Keys.KEY_POST_MANY_UNI_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PostManyUniRecord>> getKeys() {
        return Arrays.<UniqueKey<PostManyUniRecord>>asList(Keys.KEY_POST_MANY_UNI_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostManyUni as(String alias) {
        return new PostManyUni(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostManyUni as(Name alias) {
        return new PostManyUni(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PostManyUni rename(String name) {
        return new PostManyUni(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PostManyUni rename(Name name) {
        return new PostManyUni(name, null);
    }
}
