/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.PostDetailsOneBiRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostDetailsOneBi extends TableImpl<PostDetailsOneBiRecord> {

    private static final long serialVersionUID = -1948610918;

    /**
     * The reference instance of <code>hi_perf_java_pers.post_details_one_bi</code>
     */
    public static final PostDetailsOneBi POST_DETAILS_ONE_BI = new PostDetailsOneBi();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PostDetailsOneBiRecord> getRecordType() {
        return PostDetailsOneBiRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.post_details_one_bi.details</code>.
     */
    public final TableField<PostDetailsOneBiRecord, String> DETAILS = createField("details", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>hi_perf_java_pers.post_details_one_bi.post_id</code>.
     */
    public final TableField<PostDetailsOneBiRecord, Long> POST_ID = createField("post_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>hi_perf_java_pers.post_details_one_bi</code> table reference
     */
    public PostDetailsOneBi() {
        this(DSL.name("post_details_one_bi"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.post_details_one_bi</code> table reference
     */
    public PostDetailsOneBi(String alias) {
        this(DSL.name(alias), POST_DETAILS_ONE_BI);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.post_details_one_bi</code> table reference
     */
    public PostDetailsOneBi(Name alias) {
        this(alias, POST_DETAILS_ONE_BI);
    }

    private PostDetailsOneBi(Name alias, Table<PostDetailsOneBiRecord> aliased) {
        this(alias, aliased, null);
    }

    private PostDetailsOneBi(Name alias, Table<PostDetailsOneBiRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PostDetailsOneBi(Table<O> child, ForeignKey<O, PostDetailsOneBiRecord> key) {
        super(child, key, POST_DETAILS_ONE_BI);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.POST_DETAILS_ONE_BI_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PostDetailsOneBiRecord> getPrimaryKey() {
        return Keys.KEY_POST_DETAILS_ONE_BI_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PostDetailsOneBiRecord>> getKeys() {
        return Arrays.<UniqueKey<PostDetailsOneBiRecord>>asList(Keys.KEY_POST_DETAILS_ONE_BI_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PostDetailsOneBiRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PostDetailsOneBiRecord, ?>>asList(Keys.FKSBVJ5N18KTN1LC7A1UC1AUJI0);
    }

    public PostOneToOneBi postOneToOneBi() {
        return new PostOneToOneBi(this, Keys.FKSBVJ5N18KTN1LC7A1UC1AUJI0);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostDetailsOneBi as(String alias) {
        return new PostDetailsOneBi(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostDetailsOneBi as(Name alias) {
        return new PostDetailsOneBi(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PostDetailsOneBi rename(String name) {
        return new PostDetailsOneBi(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PostDetailsOneBi rename(Name name) {
        return new PostDetailsOneBi(name, null);
    }
}
