/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.PostWithCollectionRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostWithCollection extends TableImpl<PostWithCollectionRecord> {

    private static final long serialVersionUID = -1303621611;

    /**
     * The reference instance of <code>hi_perf_java_pers.post_with_collection</code>
     */
    public static final PostWithCollection POST_WITH_COLLECTION = new PostWithCollection();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PostWithCollectionRecord> getRecordType() {
        return PostWithCollectionRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.post_with_collection.id</code>.
     */
    public final TableField<PostWithCollectionRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * Create a <code>hi_perf_java_pers.post_with_collection</code> table reference
     */
    public PostWithCollection() {
        this(DSL.name("post_with_collection"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.post_with_collection</code> table reference
     */
    public PostWithCollection(String alias) {
        this(DSL.name(alias), POST_WITH_COLLECTION);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.post_with_collection</code> table reference
     */
    public PostWithCollection(Name alias) {
        this(alias, POST_WITH_COLLECTION);
    }

    private PostWithCollection(Name alias, Table<PostWithCollectionRecord> aliased) {
        this(alias, aliased, null);
    }

    private PostWithCollection(Name alias, Table<PostWithCollectionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PostWithCollection(Table<O> child, ForeignKey<O, PostWithCollectionRecord> key) {
        super(child, key, POST_WITH_COLLECTION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.POST_WITH_COLLECTION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PostWithCollectionRecord, Long> getIdentity() {
        return Keys.IDENTITY_POST_WITH_COLLECTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PostWithCollectionRecord> getPrimaryKey() {
        return Keys.KEY_POST_WITH_COLLECTION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PostWithCollectionRecord>> getKeys() {
        return Arrays.<UniqueKey<PostWithCollectionRecord>>asList(Keys.KEY_POST_WITH_COLLECTION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostWithCollection as(String alias) {
        return new PostWithCollection(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostWithCollection as(Name alias) {
        return new PostWithCollection(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PostWithCollection rename(String name) {
        return new PostWithCollection(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PostWithCollection rename(Name name) {
        return new PostWithCollection(name, null);
    }
}
