/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.PostOneRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostOne extends TableImpl<PostOneRecord> {

    private static final long serialVersionUID = -461584601;

    /**
     * The reference instance of <code>hi_perf_java_pers.post_one</code>
     */
    public static final PostOne POST_ONE = new PostOne();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PostOneRecord> getRecordType() {
        return PostOneRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.post_one.id</code>.
     */
    public final TableField<PostOneRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>hi_perf_java_pers.post_one.content</code>.
     */
    public final TableField<PostOneRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>hi_perf_java_pers.post_one.four</code>.
     */
    public final TableField<PostOneRecord, Double> FOUR = createField("four", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>hi_perf_java_pers.post_one.one</code>.
     */
    public final TableField<PostOneRecord, Integer> ONE = createField("one", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>hi_perf_java_pers.post_one.three</code>.
     */
    public final TableField<PostOneRecord, Long> THREE = createField("three", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>hi_perf_java_pers.post_one.two</code>.
     */
    public final TableField<PostOneRecord, String> TWO = createField("two", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>hi_perf_java_pers.post_one</code> table reference
     */
    public PostOne() {
        this(DSL.name("post_one"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.post_one</code> table reference
     */
    public PostOne(String alias) {
        this(DSL.name(alias), POST_ONE);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.post_one</code> table reference
     */
    public PostOne(Name alias) {
        this(alias, POST_ONE);
    }

    private PostOne(Name alias, Table<PostOneRecord> aliased) {
        this(alias, aliased, null);
    }

    private PostOne(Name alias, Table<PostOneRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PostOne(Table<O> child, ForeignKey<O, PostOneRecord> key) {
        super(child, key, POST_ONE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.POST_ONE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PostOneRecord, Long> getIdentity() {
        return Keys.IDENTITY_POST_ONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PostOneRecord> getPrimaryKey() {
        return Keys.KEY_POST_ONE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PostOneRecord>> getKeys() {
        return Arrays.<UniqueKey<PostOneRecord>>asList(Keys.KEY_POST_ONE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostOne as(String alias) {
        return new PostOne(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostOne as(Name alias) {
        return new PostOne(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PostOne rename(String name) {
        return new PostOne(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PostOne rename(Name name) {
        return new PostOne(name, null);
    }
}
