/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.PostOneBiRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostOneBi extends TableImpl<PostOneBiRecord> {

    private static final long serialVersionUID = -28393311;

    /**
     * The reference instance of <code>hi_perf_java_pers.post_one_bi</code>
     */
    public static final PostOneBi POST_ONE_BI = new PostOneBi();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PostOneBiRecord> getRecordType() {
        return PostOneBiRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.post_one_bi.id</code>.
     */
    public final TableField<PostOneBiRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>hi_perf_java_pers.post_one_bi.enumeration</code>.
     */
    public final TableField<PostOneBiRecord, String> ENUMERATION = createField("enumeration", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>hi_perf_java_pers.post_one_bi</code> table reference
     */
    public PostOneBi() {
        this(DSL.name("post_one_bi"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.post_one_bi</code> table reference
     */
    public PostOneBi(String alias) {
        this(DSL.name(alias), POST_ONE_BI);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.post_one_bi</code> table reference
     */
    public PostOneBi(Name alias) {
        this(alias, POST_ONE_BI);
    }

    private PostOneBi(Name alias, Table<PostOneBiRecord> aliased) {
        this(alias, aliased, null);
    }

    private PostOneBi(Name alias, Table<PostOneBiRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PostOneBi(Table<O> child, ForeignKey<O, PostOneBiRecord> key) {
        super(child, key, POST_ONE_BI);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.POST_ONE_BI_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PostOneBiRecord, Long> getIdentity() {
        return Keys.IDENTITY_POST_ONE_BI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PostOneBiRecord> getPrimaryKey() {
        return Keys.KEY_POST_ONE_BI_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PostOneBiRecord>> getKeys() {
        return Arrays.<UniqueKey<PostOneBiRecord>>asList(Keys.KEY_POST_ONE_BI_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostOneBi as(String alias) {
        return new PostOneBi(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostOneBi as(Name alias) {
        return new PostOneBi(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PostOneBi rename(String name) {
        return new PostOneBi(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PostOneBi rename(Name name) {
        return new PostOneBi(name, null);
    }
}
