/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.PostOneUniRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostOneUni extends TableImpl<PostOneUniRecord> {

    private static final long serialVersionUID = 672409698;

    /**
     * The reference instance of <code>hi_perf_java_pers.post_one_uni</code>
     */
    public static final PostOneUni POST_ONE_UNI = new PostOneUni();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PostOneUniRecord> getRecordType() {
        return PostOneUniRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.post_one_uni.id1</code>.
     */
    public final TableField<PostOneUniRecord, Long> ID1 = createField("id1", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>hi_perf_java_pers.post_one_uni.id2</code>.
     */
    public final TableField<PostOneUniRecord, Long> ID2 = createField("id2", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>hi_perf_java_pers.post_one_uni.attrib1</code>.
     */
    public final TableField<PostOneUniRecord, String> ATTRIB1 = createField("attrib1", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>hi_perf_java_pers.post_one_uni.attrib2</code>.
     */
    public final TableField<PostOneUniRecord, Integer> ATTRIB2 = createField("attrib2", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>hi_perf_java_pers.post_one_uni.attrib3</code>.
     */
    public final TableField<PostOneUniRecord, Double> ATTRIB3 = createField("attrib3", org.jooq.impl.SQLDataType.FLOAT, this, "");

    /**
     * The column <code>hi_perf_java_pers.post_one_uni.version</code>.
     */
    public final TableField<PostOneUniRecord, Integer> VERSION = createField("version", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>hi_perf_java_pers.post_one_uni</code> table reference
     */
    public PostOneUni() {
        this(DSL.name("post_one_uni"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.post_one_uni</code> table reference
     */
    public PostOneUni(String alias) {
        this(DSL.name(alias), POST_ONE_UNI);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.post_one_uni</code> table reference
     */
    public PostOneUni(Name alias) {
        this(alias, POST_ONE_UNI);
    }

    private PostOneUni(Name alias, Table<PostOneUniRecord> aliased) {
        this(alias, aliased, null);
    }

    private PostOneUni(Name alias, Table<PostOneUniRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PostOneUni(Table<O> child, ForeignKey<O, PostOneUniRecord> key) {
        super(child, key, POST_ONE_UNI);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.POST_ONE_UNI_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PostOneUniRecord> getPrimaryKey() {
        return Keys.KEY_POST_ONE_UNI_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PostOneUniRecord>> getKeys() {
        return Arrays.<UniqueKey<PostOneUniRecord>>asList(Keys.KEY_POST_ONE_UNI_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostOneUni as(String alias) {
        return new PostOneUni(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostOneUni as(Name alias) {
        return new PostOneUni(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PostOneUni rename(String name) {
        return new PostOneUni(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PostOneUni rename(Name name) {
        return new PostOneUni(name, null);
    }
}
