/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.PostDetailsOneRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostDetailsOne extends TableImpl<PostDetailsOneRecord> {

    private static final long serialVersionUID = 1615505092;

    /**
     * The reference instance of <code>hi_perf_java_pers.post_details_one</code>
     */
    public static final PostDetailsOne POST_DETAILS_ONE = new PostDetailsOne();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PostDetailsOneRecord> getRecordType() {
        return PostDetailsOneRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.post_details_one.details</code>.
     */
    public final TableField<PostDetailsOneRecord, String> DETAILS = createField("details", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>hi_perf_java_pers.post_details_one.post_id</code>.
     */
    public final TableField<PostDetailsOneRecord, Long> POST_ID = createField("post_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>hi_perf_java_pers.post_details_one</code> table reference
     */
    public PostDetailsOne() {
        this(DSL.name("post_details_one"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.post_details_one</code> table reference
     */
    public PostDetailsOne(String alias) {
        this(DSL.name(alias), POST_DETAILS_ONE);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.post_details_one</code> table reference
     */
    public PostDetailsOne(Name alias) {
        this(alias, POST_DETAILS_ONE);
    }

    private PostDetailsOne(Name alias, Table<PostDetailsOneRecord> aliased) {
        this(alias, aliased, null);
    }

    private PostDetailsOne(Name alias, Table<PostDetailsOneRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PostDetailsOne(Table<O> child, ForeignKey<O, PostDetailsOneRecord> key) {
        super(child, key, POST_DETAILS_ONE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.POST_DETAILS_ONE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PostDetailsOneRecord> getPrimaryKey() {
        return Keys.KEY_POST_DETAILS_ONE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PostDetailsOneRecord>> getKeys() {
        return Arrays.<UniqueKey<PostDetailsOneRecord>>asList(Keys.KEY_POST_DETAILS_ONE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PostDetailsOneRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PostDetailsOneRecord, ?>>asList(Keys.FK8VWH77YWL2HRLWQSIETMRAOB0);
    }

    public PostOneToOne postOneToOne() {
        return new PostOneToOne(this, Keys.FK8VWH77YWL2HRLWQSIETMRAOB0);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostDetailsOne as(String alias) {
        return new PostDetailsOne(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostDetailsOne as(Name alias) {
        return new PostDetailsOne(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PostDetailsOne rename(String name) {
        return new PostDetailsOne(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PostDetailsOne rename(Name name) {
        return new PostDetailsOne(name, null);
    }
}
