/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.PostOneToOneRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostOneToOne extends TableImpl<PostOneToOneRecord> {

    private static final long serialVersionUID = 1955303128;

    /**
     * The reference instance of <code>hi_perf_java_pers.post_one_to_one</code>
     */
    public static final PostOneToOne POST_ONE_TO_ONE = new PostOneToOne();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PostOneToOneRecord> getRecordType() {
        return PostOneToOneRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.post_one_to_one.id</code>.
     */
    public final TableField<PostOneToOneRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>hi_perf_java_pers.post_one_to_one.content</code>.
     */
    public final TableField<PostOneToOneRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>hi_perf_java_pers.post_one_to_one</code> table reference
     */
    public PostOneToOne() {
        this(DSL.name("post_one_to_one"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.post_one_to_one</code> table reference
     */
    public PostOneToOne(String alias) {
        this(DSL.name(alias), POST_ONE_TO_ONE);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.post_one_to_one</code> table reference
     */
    public PostOneToOne(Name alias) {
        this(alias, POST_ONE_TO_ONE);
    }

    private PostOneToOne(Name alias, Table<PostOneToOneRecord> aliased) {
        this(alias, aliased, null);
    }

    private PostOneToOne(Name alias, Table<PostOneToOneRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PostOneToOne(Table<O> child, ForeignKey<O, PostOneToOneRecord> key) {
        super(child, key, POST_ONE_TO_ONE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.POST_ONE_TO_ONE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PostOneToOneRecord, Long> getIdentity() {
        return Keys.IDENTITY_POST_ONE_TO_ONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PostOneToOneRecord> getPrimaryKey() {
        return Keys.KEY_POST_ONE_TO_ONE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PostOneToOneRecord>> getKeys() {
        return Arrays.<UniqueKey<PostOneToOneRecord>>asList(Keys.KEY_POST_ONE_TO_ONE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostOneToOne as(String alias) {
        return new PostOneToOne(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostOneToOne as(Name alias) {
        return new PostOneToOne(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PostOneToOne rename(String name) {
        return new PostOneToOne(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PostOneToOne rename(Name name) {
        return new PostOneToOne(name, null);
    }
}
