/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.SequenceGeneratorRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SequenceGenerator extends TableImpl<SequenceGeneratorRecord> {

    private static final long serialVersionUID = 45461216;

    /**
     * The reference instance of <code>hi_perf_java_pers.sequence_generator</code>
     */
    public static final SequenceGenerator SEQUENCE_GENERATOR = new SequenceGenerator();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SequenceGeneratorRecord> getRecordType() {
        return SequenceGeneratorRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.sequence_generator.id</code>.
     */
    public final TableField<SequenceGeneratorRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>hi_perf_java_pers.sequence_generator</code> table reference
     */
    public SequenceGenerator() {
        this(DSL.name("sequence_generator"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.sequence_generator</code> table reference
     */
    public SequenceGenerator(String alias) {
        this(DSL.name(alias), SEQUENCE_GENERATOR);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.sequence_generator</code> table reference
     */
    public SequenceGenerator(Name alias) {
        this(alias, SEQUENCE_GENERATOR);
    }

    private SequenceGenerator(Name alias, Table<SequenceGeneratorRecord> aliased) {
        this(alias, aliased, null);
    }

    private SequenceGenerator(Name alias, Table<SequenceGeneratorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> SequenceGenerator(Table<O> child, ForeignKey<O, SequenceGeneratorRecord> key) {
        super(child, key, SEQUENCE_GENERATOR);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SEQUENCE_GENERATOR_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SequenceGeneratorRecord> getPrimaryKey() {
        return Keys.KEY_SEQUENCE_GENERATOR_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SequenceGeneratorRecord>> getKeys() {
        return Arrays.<UniqueKey<SequenceGeneratorRecord>>asList(Keys.KEY_SEQUENCE_GENERATOR_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SequenceGenerator as(String alias) {
        return new SequenceGenerator(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SequenceGenerator as(Name alias) {
        return new SequenceGenerator(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SequenceGenerator rename(String name) {
        return new SequenceGenerator(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SequenceGenerator rename(Name name) {
        return new SequenceGenerator(name, null);
    }
}
