/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.StandaloneEntityRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StandaloneEntity extends TableImpl<StandaloneEntityRecord> {

    private static final long serialVersionUID = 520210863;

    /**
     * The reference instance of <code>hi_perf_java_pers.standalone_entity</code>
     */
    public static final StandaloneEntity STANDALONE_ENTITY = new StandaloneEntity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StandaloneEntityRecord> getRecordType() {
        return StandaloneEntityRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.standalone_entity.id</code>.
     */
    public final TableField<StandaloneEntityRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>hi_perf_java_pers.standalone_entity.name</code>.
     */
    public final TableField<StandaloneEntityRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>hi_perf_java_pers.standalone_entity</code> table reference
     */
    public StandaloneEntity() {
        this(DSL.name("standalone_entity"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.standalone_entity</code> table reference
     */
    public StandaloneEntity(String alias) {
        this(DSL.name(alias), STANDALONE_ENTITY);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.standalone_entity</code> table reference
     */
    public StandaloneEntity(Name alias) {
        this(alias, STANDALONE_ENTITY);
    }

    private StandaloneEntity(Name alias, Table<StandaloneEntityRecord> aliased) {
        this(alias, aliased, null);
    }

    private StandaloneEntity(Name alias, Table<StandaloneEntityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> StandaloneEntity(Table<O> child, ForeignKey<O, StandaloneEntityRecord> key) {
        super(child, key, STANDALONE_ENTITY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.STANDALONE_ENTITY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StandaloneEntityRecord> getPrimaryKey() {
        return Keys.KEY_STANDALONE_ENTITY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StandaloneEntityRecord>> getKeys() {
        return Arrays.<UniqueKey<StandaloneEntityRecord>>asList(Keys.KEY_STANDALONE_ENTITY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StandaloneEntity as(String alias) {
        return new StandaloneEntity(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StandaloneEntity as(Name alias) {
        return new StandaloneEntity(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StandaloneEntity rename(String name) {
        return new StandaloneEntity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StandaloneEntity rename(Name name) {
        return new StandaloneEntity(name, null);
    }
}
