/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.TableGeneratorRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TableGenerator extends TableImpl<TableGeneratorRecord> {

    private static final long serialVersionUID = -1376505607;

    /**
     * The reference instance of <code>hi_perf_java_pers.table_generator</code>
     */
    public static final TableGenerator TABLE_GENERATOR = new TableGenerator();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TableGeneratorRecord> getRecordType() {
        return TableGeneratorRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.table_generator.id</code>.
     */
    public final TableField<TableGeneratorRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>hi_perf_java_pers.table_generator</code> table reference
     */
    public TableGenerator() {
        this(DSL.name("table_generator"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.table_generator</code> table reference
     */
    public TableGenerator(String alias) {
        this(DSL.name(alias), TABLE_GENERATOR);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.table_generator</code> table reference
     */
    public TableGenerator(Name alias) {
        this(alias, TABLE_GENERATOR);
    }

    private TableGenerator(Name alias, Table<TableGeneratorRecord> aliased) {
        this(alias, aliased, null);
    }

    private TableGenerator(Name alias, Table<TableGeneratorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TableGenerator(Table<O> child, ForeignKey<O, TableGeneratorRecord> key) {
        super(child, key, TABLE_GENERATOR);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TABLE_GENERATOR_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TableGeneratorRecord> getPrimaryKey() {
        return Keys.KEY_TABLE_GENERATOR_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TableGeneratorRecord>> getKeys() {
        return Arrays.<UniqueKey<TableGeneratorRecord>>asList(Keys.KEY_TABLE_GENERATOR_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableGenerator as(String alias) {
        return new TableGenerator(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableGenerator as(Name alias) {
        return new TableGenerator(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TableGenerator rename(String name) {
        return new TableGenerator(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TableGenerator rename(Name name) {
        return new TableGenerator(name, null);
    }
}
