/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.TagManyUniRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagManyUni extends TableImpl<TagManyUniRecord> {

    private static final long serialVersionUID = 815641595;

    /**
     * The reference instance of <code>hi_perf_java_pers.tag_many_uni</code>
     */
    public static final TagManyUni TAG_MANY_UNI = new TagManyUni();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TagManyUniRecord> getRecordType() {
        return TagManyUniRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.tag_many_uni.id</code>.
     */
    public final TableField<TagManyUniRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>hi_perf_java_pers.tag_many_uni.name</code>.
     */
    public final TableField<TagManyUniRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>hi_perf_java_pers.tag_many_uni</code> table reference
     */
    public TagManyUni() {
        this(DSL.name("tag_many_uni"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.tag_many_uni</code> table reference
     */
    public TagManyUni(String alias) {
        this(DSL.name(alias), TAG_MANY_UNI);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.tag_many_uni</code> table reference
     */
    public TagManyUni(Name alias) {
        this(alias, TAG_MANY_UNI);
    }

    private TagManyUni(Name alias, Table<TagManyUniRecord> aliased) {
        this(alias, aliased, null);
    }

    private TagManyUni(Name alias, Table<TagManyUniRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TagManyUni(Table<O> child, ForeignKey<O, TagManyUniRecord> key) {
        super(child, key, TAG_MANY_UNI);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TAG_MANY_UNI_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TagManyUniRecord, Long> getIdentity() {
        return Keys.IDENTITY_TAG_MANY_UNI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TagManyUniRecord> getPrimaryKey() {
        return Keys.KEY_TAG_MANY_UNI_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TagManyUniRecord>> getKeys() {
        return Arrays.<UniqueKey<TagManyUniRecord>>asList(Keys.KEY_TAG_MANY_UNI_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagManyUni as(String alias) {
        return new TagManyUni(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagManyUni as(Name alias) {
        return new TagManyUni(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TagManyUni rename(String name) {
        return new TagManyUni(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TagManyUni rename(Name name) {
        return new TagManyUni(name, null);
    }
}
