/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.vukas.jooq.db.HiPerfJavaPers;
import me.vukas.jooq.db.Indexes;
import me.vukas.jooq.db.Keys;
import me.vukas.jooq.db.tables.records.UuidgeneratorRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Uuidgenerator extends TableImpl<UuidgeneratorRecord> {

    private static final long serialVersionUID = 1088879219;

    /**
     * The reference instance of <code>hi_perf_java_pers.uuidgenerator</code>
     */
    public static final Uuidgenerator UUIDGENERATOR = new Uuidgenerator();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UuidgeneratorRecord> getRecordType() {
        return UuidgeneratorRecord.class;
    }

    /**
     * The column <code>hi_perf_java_pers.uuidgenerator.id</code>.
     */
    public final TableField<UuidgeneratorRecord, byte[]> ID = createField("id", org.jooq.impl.SQLDataType.BINARY(16).nullable(false), this, "");

    /**
     * Create a <code>hi_perf_java_pers.uuidgenerator</code> table reference
     */
    public Uuidgenerator() {
        this(DSL.name("uuidgenerator"), null);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.uuidgenerator</code> table reference
     */
    public Uuidgenerator(String alias) {
        this(DSL.name(alias), UUIDGENERATOR);
    }

    /**
     * Create an aliased <code>hi_perf_java_pers.uuidgenerator</code> table reference
     */
    public Uuidgenerator(Name alias) {
        this(alias, UUIDGENERATOR);
    }

    private Uuidgenerator(Name alias, Table<UuidgeneratorRecord> aliased) {
        this(alias, aliased, null);
    }

    private Uuidgenerator(Name alias, Table<UuidgeneratorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Uuidgenerator(Table<O> child, ForeignKey<O, UuidgeneratorRecord> key) {
        super(child, key, UUIDGENERATOR);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HiPerfJavaPers.HI_PERF_JAVA_PERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.UUIDGENERATOR_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UuidgeneratorRecord> getPrimaryKey() {
        return Keys.KEY_UUIDGENERATOR_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UuidgeneratorRecord>> getKeys() {
        return Arrays.<UniqueKey<UuidgeneratorRecord>>asList(Keys.KEY_UUIDGENERATOR_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Uuidgenerator as(String alias) {
        return new Uuidgenerator(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Uuidgenerator as(Name alias) {
        return new Uuidgenerator(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Uuidgenerator rename(String name) {
        return new Uuidgenerator(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Uuidgenerator rename(Name name) {
        return new Uuidgenerator(name, null);
    }
}
