/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables.records;


import javax.annotation.Generated;

import me.vukas.jooq.db.tables.BookManyBiAuthors;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookManyBiAuthorsRecord extends UpdatableRecordImpl<BookManyBiAuthorsRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = -1033364957;

    /**
     * Setter for <code>hi_perf_java_pers.book_many_bi_authors.books_id</code>.
     */
    public void setBooksId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.book_many_bi_authors.books_id</code>.
     */
    public Long getBooksId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>hi_perf_java_pers.book_many_bi_authors.authors_id</code>.
     */
    public void setAuthorsId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.book_many_bi_authors.authors_id</code>.
     */
    public Long getAuthorsId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return BookManyBiAuthors.BOOK_MANY_BI_AUTHORS.BOOKS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return BookManyBiAuthors.BOOK_MANY_BI_AUTHORS.AUTHORS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getBooksId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getAuthorsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getBooksId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getAuthorsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookManyBiAuthorsRecord value1(Long value) {
        setBooksId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookManyBiAuthorsRecord value2(Long value) {
        setAuthorsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookManyBiAuthorsRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookManyBiAuthorsRecord
     */
    public BookManyBiAuthorsRecord() {
        super(BookManyBiAuthors.BOOK_MANY_BI_AUTHORS);
    }

    /**
     * Create a detached, initialised BookManyBiAuthorsRecord
     */
    public BookManyBiAuthorsRecord(Long booksId, Long authorsId) {
        super(BookManyBiAuthors.BOOK_MANY_BI_AUTHORS);

        set(0, booksId);
        set(1, authorsId);
    }
}
