/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables.records;


import javax.annotation.Generated;

import me.vukas.jooq.db.tables.BookAuthor;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookAuthorRecord extends UpdatableRecordImpl<BookAuthorRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = -1243703551;

    /**
     * Setter for <code>hi_perf_java_pers.book_author.author_id</code>.
     */
    public void setAuthorId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.book_author.author_id</code>.
     */
    public Long getAuthorId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>hi_perf_java_pers.book_author.book_id</code>.
     */
    public void setBookId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.book_author.book_id</code>.
     */
    public Long getBookId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return BookAuthor.BOOK_AUTHOR.AUTHOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return BookAuthor.BOOK_AUTHOR.BOOK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getAuthorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getBookId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getAuthorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getBookId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookAuthorRecord value1(Long value) {
        setAuthorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookAuthorRecord value2(Long value) {
        setBookId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookAuthorRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookAuthorRecord
     */
    public BookAuthorRecord() {
        super(BookAuthor.BOOK_AUTHOR);
    }

    /**
     * Create a detached, initialised BookAuthorRecord
     */
    public BookAuthorRecord(Long authorId, Long bookId) {
        super(BookAuthor.BOOK_AUTHOR);

        set(0, authorId);
        set(1, bookId);
    }
}
