/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables.records;


import javax.annotation.Generated;

import me.vukas.jooq.db.tables.Child2jt;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Child2jtRecord extends UpdatableRecordImpl<Child2jtRecord> implements Record2<String, Long> {

    private static final long serialVersionUID = -1917005236;

    /**
     * Setter for <code>hi_perf_java_pers.child2jt.child2prop</code>.
     */
    public void setChild2prop(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.child2jt.child2prop</code>.
     */
    public String getChild2prop() {
        return (String) get(0);
    }

    /**
     * Setter for <code>hi_perf_java_pers.child2jt.id</code>.
     */
    public void setId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.child2jt.id</code>.
     */
    public Long getId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Child2jt.CHILD2JT.CHILD2PROP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Child2jt.CHILD2JT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getChild2prop();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getChild2prop();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Child2jtRecord value1(String value) {
        setChild2prop(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Child2jtRecord value2(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Child2jtRecord values(String value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Child2jtRecord
     */
    public Child2jtRecord() {
        super(Child2jt.CHILD2JT);
    }

    /**
     * Create a detached, initialised Child2jtRecord
     */
    public Child2jtRecord(String child2prop, Long id) {
        super(Child2jt.CHILD2JT);

        set(0, child2prop);
        set(1, id);
    }
}
