/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables.records;


import javax.annotation.Generated;

import me.vukas.jooq.db.tables.Child1jt;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Child1jtRecord extends UpdatableRecordImpl<Child1jtRecord> implements Record2<String, Long> {

    private static final long serialVersionUID = 319306432;

    /**
     * Setter for <code>hi_perf_java_pers.child1jt.child1prop</code>.
     */
    public void setChild1prop(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.child1jt.child1prop</code>.
     */
    public String getChild1prop() {
        return (String) get(0);
    }

    /**
     * Setter for <code>hi_perf_java_pers.child1jt.id</code>.
     */
    public void setId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.child1jt.id</code>.
     */
    public Long getId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Child1jt.CHILD1JT.CHILD1PROP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Child1jt.CHILD1JT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getChild1prop();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getChild1prop();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Child1jtRecord value1(String value) {
        setChild1prop(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Child1jtRecord value2(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Child1jtRecord values(String value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Child1jtRecord
     */
    public Child1jtRecord() {
        super(Child1jt.CHILD1JT);
    }

    /**
     * Create a detached, initialised Child1jtRecord
     */
    public Child1jtRecord(String child1prop, Long id) {
        super(Child1jt.CHILD1JT);

        set(0, child1prop);
        set(1, id);
    }
}
