/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables.records;


import javax.annotation.Generated;

import me.vukas.jooq.db.tables.PostCommentMany;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostCommentManyRecord extends UpdatableRecordImpl<PostCommentManyRecord> implements Record7<Long, String, Double, Integer, Long, String, Long> {

    private static final long serialVersionUID = -1961748164;

    /**
     * Setter for <code>hi_perf_java_pers.post_comment_many.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_comment_many.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>hi_perf_java_pers.post_comment_many.comment</code>.
     */
    public void setComment(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_comment_many.comment</code>.
     */
    public String getComment() {
        return (String) get(1);
    }

    /**
     * Setter for <code>hi_perf_java_pers.post_comment_many.four</code>.
     */
    public void setFour(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_comment_many.four</code>.
     */
    public Double getFour() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>hi_perf_java_pers.post_comment_many.one</code>.
     */
    public void setOne(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_comment_many.one</code>.
     */
    public Integer getOne() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>hi_perf_java_pers.post_comment_many.three</code>.
     */
    public void setThree(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_comment_many.three</code>.
     */
    public Long getThree() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>hi_perf_java_pers.post_comment_many.two</code>.
     */
    public void setTwo(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_comment_many.two</code>.
     */
    public String getTwo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>hi_perf_java_pers.post_comment_many.post_id</code>.
     */
    public void setPostId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_comment_many.post_id</code>.
     */
    public Long getPostId() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, Double, Integer, Long, String, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, Double, Integer, Long, String, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PostCommentMany.POST_COMMENT_MANY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PostCommentMany.POST_COMMENT_MANY.COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return PostCommentMany.POST_COMMENT_MANY.FOUR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return PostCommentMany.POST_COMMENT_MANY.ONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return PostCommentMany.POST_COMMENT_MANY.THREE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return PostCommentMany.POST_COMMENT_MANY.TWO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return PostCommentMany.POST_COMMENT_MANY.POST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getFour();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getOne();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getThree();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getTwo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getPostId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getFour();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getOne();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getThree();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTwo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getPostId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostCommentManyRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostCommentManyRecord value2(String value) {
        setComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostCommentManyRecord value3(Double value) {
        setFour(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostCommentManyRecord value4(Integer value) {
        setOne(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostCommentManyRecord value5(Long value) {
        setThree(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostCommentManyRecord value6(String value) {
        setTwo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostCommentManyRecord value7(Long value) {
        setPostId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostCommentManyRecord values(Long value1, String value2, Double value3, Integer value4, Long value5, String value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostCommentManyRecord
     */
    public PostCommentManyRecord() {
        super(PostCommentMany.POST_COMMENT_MANY);
    }

    /**
     * Create a detached, initialised PostCommentManyRecord
     */
    public PostCommentManyRecord(Long id, String comment, Double four, Integer one, Long three, String two, Long postId) {
        super(PostCommentMany.POST_COMMENT_MANY);

        set(0, id);
        set(1, comment);
        set(2, four);
        set(3, one);
        set(4, three);
        set(5, two);
        set(6, postId);
    }
}
