/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables.records;


import javax.annotation.Generated;

import me.vukas.jooq.db.tables.PostWithCollectionListOfStrings;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostWithCollectionListOfStringsRecord extends TableRecordImpl<PostWithCollectionListOfStringsRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 32726484;

    /**
     * Setter for <code>hi_perf_java_pers.post_with_collection_list_of_strings.post_with_collection_id</code>.
     */
    public void setPostWithCollectionId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_with_collection_list_of_strings.post_with_collection_id</code>.
     */
    public Long getPostWithCollectionId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>hi_perf_java_pers.post_with_collection_list_of_strings.list_of_strings</code>.
     */
    public void setListOfStrings(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_with_collection_list_of_strings.list_of_strings</code>.
     */
    public String getListOfStrings() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PostWithCollectionListOfStrings.POST_WITH_COLLECTION_LIST_OF_STRINGS.POST_WITH_COLLECTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PostWithCollectionListOfStrings.POST_WITH_COLLECTION_LIST_OF_STRINGS.LIST_OF_STRINGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getPostWithCollectionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getListOfStrings();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getPostWithCollectionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getListOfStrings();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostWithCollectionListOfStringsRecord value1(Long value) {
        setPostWithCollectionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostWithCollectionListOfStringsRecord value2(String value) {
        setListOfStrings(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostWithCollectionListOfStringsRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostWithCollectionListOfStringsRecord
     */
    public PostWithCollectionListOfStringsRecord() {
        super(PostWithCollectionListOfStrings.POST_WITH_COLLECTION_LIST_OF_STRINGS);
    }

    /**
     * Create a detached, initialised PostWithCollectionListOfStringsRecord
     */
    public PostWithCollectionListOfStringsRecord(Long postWithCollectionId, String listOfStrings) {
        super(PostWithCollectionListOfStrings.POST_WITH_COLLECTION_LIST_OF_STRINGS);

        set(0, postWithCollectionId);
        set(1, listOfStrings);
    }
}
