/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables.records;


import javax.annotation.Generated;

import me.vukas.jooq.db.tables.PostOneBi;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostOneBiRecord extends UpdatableRecordImpl<PostOneBiRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = -221422652;

    /**
     * Setter for <code>hi_perf_java_pers.post_one_bi.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_one_bi.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>hi_perf_java_pers.post_one_bi.enumeration</code>.
     */
    public void setEnumeration(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_one_bi.enumeration</code>.
     */
    public String getEnumeration() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PostOneBi.POST_ONE_BI.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PostOneBi.POST_ONE_BI.ENUMERATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getEnumeration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEnumeration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostOneBiRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostOneBiRecord value2(String value) {
        setEnumeration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostOneBiRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostOneBiRecord
     */
    public PostOneBiRecord() {
        super(PostOneBi.POST_ONE_BI);
    }

    /**
     * Create a detached, initialised PostOneBiRecord
     */
    public PostOneBiRecord(Long id, String enumeration) {
        super(PostOneBi.POST_ONE_BI);

        set(0, id);
        set(1, enumeration);
    }
}
