/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables.records;


import javax.annotation.Generated;

import me.vukas.jooq.db.tables.PostCommentUniMany;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostCommentUniManyRecord extends UpdatableRecordImpl<PostCommentUniManyRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = -1198065690;

    /**
     * Setter for <code>hi_perf_java_pers.post_comment_uni_many.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_comment_uni_many.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>hi_perf_java_pers.post_comment_uni_many.post_id1</code>.
     */
    public void setPostId1(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_comment_uni_many.post_id1</code>.
     */
    public Long getPostId1() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>hi_perf_java_pers.post_comment_uni_many.post_id2</code>.
     */
    public void setPostId2(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_comment_uni_many.post_id2</code>.
     */
    public Long getPostId2() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PostCommentUniMany.POST_COMMENT_UNI_MANY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PostCommentUniMany.POST_COMMENT_UNI_MANY.POST_ID1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return PostCommentUniMany.POST_COMMENT_UNI_MANY.POST_ID2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getPostId1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getPostId2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPostId1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getPostId2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostCommentUniManyRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostCommentUniManyRecord value2(Long value) {
        setPostId1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostCommentUniManyRecord value3(Long value) {
        setPostId2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostCommentUniManyRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostCommentUniManyRecord
     */
    public PostCommentUniManyRecord() {
        super(PostCommentUniMany.POST_COMMENT_UNI_MANY);
    }

    /**
     * Create a detached, initialised PostCommentUniManyRecord
     */
    public PostCommentUniManyRecord(Long id, Long postId1, Long postId2) {
        super(PostCommentUniMany.POST_COMMENT_UNI_MANY);

        set(0, id);
        set(1, postId1);
        set(2, postId2);
    }
}
