/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables.records;


import javax.annotation.Generated;

import me.vukas.jooq.db.tables.PostManyUniTags;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostManyUniTagsRecord extends UpdatableRecordImpl<PostManyUniTagsRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1073013553;

    /**
     * Setter for <code>hi_perf_java_pers.post_many_uni_tags.post_many_uni_id</code>.
     */
    public void setPostManyUniId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_many_uni_tags.post_many_uni_id</code>.
     */
    public Long getPostManyUniId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>hi_perf_java_pers.post_many_uni_tags.tags_id</code>.
     */
    public void setTagsId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_many_uni_tags.tags_id</code>.
     */
    public Long getTagsId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PostManyUniTags.POST_MANY_UNI_TAGS.POST_MANY_UNI_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PostManyUniTags.POST_MANY_UNI_TAGS.TAGS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getPostManyUniId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getTagsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getPostManyUniId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getTagsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostManyUniTagsRecord value1(Long value) {
        setPostManyUniId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostManyUniTagsRecord value2(Long value) {
        setTagsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostManyUniTagsRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostManyUniTagsRecord
     */
    public PostManyUniTagsRecord() {
        super(PostManyUniTags.POST_MANY_UNI_TAGS);
    }

    /**
     * Create a detached, initialised PostManyUniTagsRecord
     */
    public PostManyUniTagsRecord(Long postManyUniId, Long tagsId) {
        super(PostManyUniTags.POST_MANY_UNI_TAGS);

        set(0, postManyUniId);
        set(1, tagsId);
    }
}
