/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables.records;


import javax.annotation.Generated;

import me.vukas.jooq.db.tables.PostOneUni;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostOneUniRecord extends UpdatableRecordImpl<PostOneUniRecord> implements Record6<Long, Long, String, Integer, Double, Integer> {

    private static final long serialVersionUID = 1681493863;

    /**
     * Setter for <code>hi_perf_java_pers.post_one_uni.id1</code>.
     */
    public void setId1(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_one_uni.id1</code>.
     */
    public Long getId1() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>hi_perf_java_pers.post_one_uni.id2</code>.
     */
    public void setId2(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_one_uni.id2</code>.
     */
    public Long getId2() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>hi_perf_java_pers.post_one_uni.attrib1</code>.
     */
    public void setAttrib1(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_one_uni.attrib1</code>.
     */
    public String getAttrib1() {
        return (String) get(2);
    }

    /**
     * Setter for <code>hi_perf_java_pers.post_one_uni.attrib2</code>.
     */
    public void setAttrib2(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_one_uni.attrib2</code>.
     */
    public Integer getAttrib2() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>hi_perf_java_pers.post_one_uni.attrib3</code>.
     */
    public void setAttrib3(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_one_uni.attrib3</code>.
     */
    public Double getAttrib3() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>hi_perf_java_pers.post_one_uni.version</code>.
     */
    public void setVersion(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_one_uni.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, String, Integer, Double, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, String, Integer, Double, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PostOneUni.POST_ONE_UNI.ID1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PostOneUni.POST_ONE_UNI.ID2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PostOneUni.POST_ONE_UNI.ATTRIB1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return PostOneUni.POST_ONE_UNI.ATTRIB2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return PostOneUni.POST_ONE_UNI.ATTRIB3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return PostOneUni.POST_ONE_UNI.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getId2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAttrib1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getAttrib2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getAttrib3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getId2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAttrib1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAttrib2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getAttrib3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostOneUniRecord value1(Long value) {
        setId1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostOneUniRecord value2(Long value) {
        setId2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostOneUniRecord value3(String value) {
        setAttrib1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostOneUniRecord value4(Integer value) {
        setAttrib2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostOneUniRecord value5(Double value) {
        setAttrib3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostOneUniRecord value6(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostOneUniRecord values(Long value1, Long value2, String value3, Integer value4, Double value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostOneUniRecord
     */
    public PostOneUniRecord() {
        super(PostOneUni.POST_ONE_UNI);
    }

    /**
     * Create a detached, initialised PostOneUniRecord
     */
    public PostOneUniRecord(Long id1, Long id2, String attrib1, Integer attrib2, Double attrib3, Integer version) {
        super(PostOneUni.POST_ONE_UNI);

        set(0, id1);
        set(1, id2);
        set(2, attrib1);
        set(3, attrib2);
        set(4, attrib3);
        set(5, version);
    }
}
