/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables.records;


import javax.annotation.Generated;

import me.vukas.jooq.db.tables.PostDetailsOne;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostDetailsOneRecord extends UpdatableRecordImpl<PostDetailsOneRecord> implements Record2<String, Long> {

    private static final long serialVersionUID = 68914655;

    /**
     * Setter for <code>hi_perf_java_pers.post_details_one.details</code>.
     */
    public void setDetails(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_details_one.details</code>.
     */
    public String getDetails() {
        return (String) get(0);
    }

    /**
     * Setter for <code>hi_perf_java_pers.post_details_one.post_id</code>.
     */
    public void setPostId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.post_details_one.post_id</code>.
     */
    public Long getPostId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return PostDetailsOne.POST_DETAILS_ONE.DETAILS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PostDetailsOne.POST_DETAILS_ONE.POST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getDetails();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getPostId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getDetails();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPostId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostDetailsOneRecord value1(String value) {
        setDetails(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostDetailsOneRecord value2(Long value) {
        setPostId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostDetailsOneRecord values(String value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostDetailsOneRecord
     */
    public PostDetailsOneRecord() {
        super(PostDetailsOne.POST_DETAILS_ONE);
    }

    /**
     * Create a detached, initialised PostDetailsOneRecord
     */
    public PostDetailsOneRecord(String details, Long postId) {
        super(PostDetailsOne.POST_DETAILS_ONE);

        set(0, details);
        set(1, postId);
    }
}
