/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db.tables.records;


import javax.annotation.Generated;

import me.vukas.jooq.db.tables.Uuidgenerator;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UuidgeneratorRecord extends UpdatableRecordImpl<UuidgeneratorRecord> implements Record1<byte[]> {

    private static final long serialVersionUID = -1630810486;

    /**
     * Setter for <code>hi_perf_java_pers.uuidgenerator.id</code>.
     */
    public void setId(byte... value) {
        set(0, value);
    }

    /**
     * Getter for <code>hi_perf_java_pers.uuidgenerator.id</code>.
     */
    public byte[] getId() {
        return (byte[]) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<byte[]> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<byte[]> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<byte[]> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field1() {
        return Uuidgenerator.UUIDGENERATOR.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UuidgeneratorRecord value1(byte... value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UuidgeneratorRecord values(byte[] value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UuidgeneratorRecord
     */
    public UuidgeneratorRecord() {
        super(Uuidgenerator.UUIDGENERATOR);
    }

    /**
     * Create a detached, initialised UuidgeneratorRecord
     */
    public UuidgeneratorRecord(byte[] id) {
        super(Uuidgenerator.UUIDGENERATOR);

        set(0, id);
    }
}
