/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db;


import javax.annotation.Generated;

import me.vukas.jooq.db.tables.Assigneduuidgenerator;
import me.vukas.jooq.db.tables.AuthorManyBi;
import me.vukas.jooq.db.tables.AuthorManyj;
import me.vukas.jooq.db.tables.BookAuthor;
import me.vukas.jooq.db.tables.BookManyBi;
import me.vukas.jooq.db.tables.BookManyBiAuthors;
import me.vukas.jooq.db.tables.BookManyj;
import me.vukas.jooq.db.tables.Child1jt;
import me.vukas.jooq.db.tables.Child1ms;
import me.vukas.jooq.db.tables.Child1tpc;
import me.vukas.jooq.db.tables.Child2jt;
import me.vukas.jooq.db.tables.Child2ms;
import me.vukas.jooq.db.tables.Child2tpc;
import me.vukas.jooq.db.tables.HibernateSequences;
import me.vukas.jooq.db.tables.IdentityGenerator;
import me.vukas.jooq.db.tables.ParentJt;
import me.vukas.jooq.db.tables.ParentSt;
import me.vukas.jooq.db.tables.Parenttpc;
import me.vukas.jooq.db.tables.PooledSequenceGenerator;
import me.vukas.jooq.db.tables.PostCommentMany;
import me.vukas.jooq.db.tables.PostCommentManyBi;
import me.vukas.jooq.db.tables.PostCommentUniMany;
import me.vukas.jooq.db.tables.PostDetailsOne;
import me.vukas.jooq.db.tables.PostDetailsOneBi;
import me.vukas.jooq.db.tables.PostManyUni;
import me.vukas.jooq.db.tables.PostManyUniTags;
import me.vukas.jooq.db.tables.PostOne;
import me.vukas.jooq.db.tables.PostOneBi;
import me.vukas.jooq.db.tables.PostOneToOne;
import me.vukas.jooq.db.tables.PostOneToOneBi;
import me.vukas.jooq.db.tables.PostOneUni;
import me.vukas.jooq.db.tables.PostWithCollection;
import me.vukas.jooq.db.tables.PostWithCollectionListOfComplex;
import me.vukas.jooq.db.tables.PostWithCollectionListOfStrings;
import me.vukas.jooq.db.tables.SequenceGenerator;
import me.vukas.jooq.db.tables.StandaloneEntity;
import me.vukas.jooq.db.tables.TableGenerator;
import me.vukas.jooq.db.tables.TagManyUni;
import me.vukas.jooq.db.tables.Uuidgenerator;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>hi_perf_java_pers</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ASSIGNEDUUIDGENERATOR_PRIMARY = Indexes0.ASSIGNEDUUIDGENERATOR_PRIMARY;
    public static final Index AUTHOR_MANYJ_PRIMARY = Indexes0.AUTHOR_MANYJ_PRIMARY;
    public static final Index AUTHOR_MANY_BI_PRIMARY = Indexes0.AUTHOR_MANY_BI_PRIMARY;
    public static final Index AUTHOR_MANY_BI_UK_81A5W9QC9SSM6XLY74RM34B4A = Indexes0.AUTHOR_MANY_BI_UK_81A5W9QC9SSM6XLY74RM34B4A;
    public static final Index BOOK_AUTHOR_FKBO8DRQ2LKNC77OLAJ3KKBJH4 = Indexes0.BOOK_AUTHOR_FKBO8DRQ2LKNC77OLAJ3KKBJH4;
    public static final Index BOOK_AUTHOR_PRIMARY = Indexes0.BOOK_AUTHOR_PRIMARY;
    public static final Index BOOK_MANYJ_PRIMARY = Indexes0.BOOK_MANYJ_PRIMARY;
    public static final Index BOOK_MANY_BI_PRIMARY = Indexes0.BOOK_MANY_BI_PRIMARY;
    public static final Index BOOK_MANY_BI_AUTHORS_FKA9KDM0F4X1KPV93HJW2E296HE = Indexes0.BOOK_MANY_BI_AUTHORS_FKA9KDM0F4X1KPV93HJW2E296HE;
    public static final Index BOOK_MANY_BI_AUTHORS_PRIMARY = Indexes0.BOOK_MANY_BI_AUTHORS_PRIMARY;
    public static final Index CHILD1JT_PRIMARY = Indexes0.CHILD1JT_PRIMARY;
    public static final Index CHILD1MS_PRIMARY = Indexes0.CHILD1MS_PRIMARY;
    public static final Index CHILD1TPC_PRIMARY = Indexes0.CHILD1TPC_PRIMARY;
    public static final Index CHILD2JT_PRIMARY = Indexes0.CHILD2JT_PRIMARY;
    public static final Index CHILD2MS_PRIMARY = Indexes0.CHILD2MS_PRIMARY;
    public static final Index CHILD2TPC_PRIMARY = Indexes0.CHILD2TPC_PRIMARY;
    public static final Index HIBERNATE_SEQUENCES_PRIMARY = Indexes0.HIBERNATE_SEQUENCES_PRIMARY;
    public static final Index IDENTITY_GENERATOR_PRIMARY = Indexes0.IDENTITY_GENERATOR_PRIMARY;
    public static final Index PARENTTPC_PRIMARY = Indexes0.PARENTTPC_PRIMARY;
    public static final Index PARENT_JT_PRIMARY = Indexes0.PARENT_JT_PRIMARY;
    public static final Index PARENT_ST_PRIMARY = Indexes0.PARENT_ST_PRIMARY;
    public static final Index POOLED_SEQUENCE_GENERATOR_PRIMARY = Indexes0.POOLED_SEQUENCE_GENERATOR_PRIMARY;
    public static final Index POST_COMMENT_MANY_FKIJQORVAAWMHGNKX917PS7MFP9 = Indexes0.POST_COMMENT_MANY_FKIJQORVAAWMHGNKX917PS7MFP9;
    public static final Index POST_COMMENT_MANY_PRIMARY = Indexes0.POST_COMMENT_MANY_PRIMARY;
    public static final Index POST_COMMENT_MANY_BI_FKQDJUHSGS3OPNLXT26S15U0YQF = Indexes0.POST_COMMENT_MANY_BI_FKQDJUHSGS3OPNLXT26S15U0YQF;
    public static final Index POST_COMMENT_MANY_BI_PRIMARY = Indexes0.POST_COMMENT_MANY_BI_PRIMARY;
    public static final Index POST_COMMENT_UNI_MANY_FKE4H8SRREB0UVU98PBCCFIUQ16 = Indexes0.POST_COMMENT_UNI_MANY_FKE4H8SRREB0UVU98PBCCFIUQ16;
    public static final Index POST_COMMENT_UNI_MANY_PRIMARY = Indexes0.POST_COMMENT_UNI_MANY_PRIMARY;
    public static final Index POST_DETAILS_ONE_PRIMARY = Indexes0.POST_DETAILS_ONE_PRIMARY;
    public static final Index POST_DETAILS_ONE_BI_PRIMARY = Indexes0.POST_DETAILS_ONE_BI_PRIMARY;
    public static final Index POST_MANY_UNI_PRIMARY = Indexes0.POST_MANY_UNI_PRIMARY;
    public static final Index POST_MANY_UNI_TAGS_FKNUXK5IFM2NP8MUXKNV1XOATXL = Indexes0.POST_MANY_UNI_TAGS_FKNUXK5IFM2NP8MUXKNV1XOATXL;
    public static final Index POST_MANY_UNI_TAGS_PRIMARY = Indexes0.POST_MANY_UNI_TAGS_PRIMARY;
    public static final Index POST_ONE_PRIMARY = Indexes0.POST_ONE_PRIMARY;
    public static final Index POST_ONE_BI_PRIMARY = Indexes0.POST_ONE_BI_PRIMARY;
    public static final Index POST_ONE_TO_ONE_PRIMARY = Indexes0.POST_ONE_TO_ONE_PRIMARY;
    public static final Index POST_ONE_TO_ONE_BI_PRIMARY = Indexes0.POST_ONE_TO_ONE_BI_PRIMARY;
    public static final Index POST_ONE_UNI_PRIMARY = Indexes0.POST_ONE_UNI_PRIMARY;
    public static final Index POST_WITH_COLLECTION_PRIMARY = Indexes0.POST_WITH_COLLECTION_PRIMARY;
    public static final Index POST_WITH_COLLECTION_LIST_OF_COMPLEX_FKCYYJ9CLP6U114UCY5D6TX8XH9 = Indexes0.POST_WITH_COLLECTION_LIST_OF_COMPLEX_FKCYYJ9CLP6U114UCY5D6TX8XH9;
    public static final Index POST_WITH_COLLECTION_LIST_OF_STRINGS_FKED0FRWO7QVBY7K5GPFRVWUT2I = Indexes0.POST_WITH_COLLECTION_LIST_OF_STRINGS_FKED0FRWO7QVBY7K5GPFRVWUT2I;
    public static final Index SEQUENCE_GENERATOR_PRIMARY = Indexes0.SEQUENCE_GENERATOR_PRIMARY;
    public static final Index STANDALONE_ENTITY_PRIMARY = Indexes0.STANDALONE_ENTITY_PRIMARY;
    public static final Index TABLE_GENERATOR_PRIMARY = Indexes0.TABLE_GENERATOR_PRIMARY;
    public static final Index TAG_MANY_UNI_PRIMARY = Indexes0.TAG_MANY_UNI_PRIMARY;
    public static final Index UUIDGENERATOR_PRIMARY = Indexes0.UUIDGENERATOR_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ASSIGNEDUUIDGENERATOR_PRIMARY = Internal.createIndex("PRIMARY", Assigneduuidgenerator.ASSIGNEDUUIDGENERATOR, new OrderField[] { Assigneduuidgenerator.ASSIGNEDUUIDGENERATOR.ID }, true);
        public static Index AUTHOR_MANYJ_PRIMARY = Internal.createIndex("PRIMARY", AuthorManyj.AUTHOR_MANYJ, new OrderField[] { AuthorManyj.AUTHOR_MANYJ.ID }, true);
        public static Index AUTHOR_MANY_BI_PRIMARY = Internal.createIndex("PRIMARY", AuthorManyBi.AUTHOR_MANY_BI, new OrderField[] { AuthorManyBi.AUTHOR_MANY_BI.ID }, true);
        public static Index AUTHOR_MANY_BI_UK_81A5W9QC9SSM6XLY74RM34B4A = Internal.createIndex("UK_81a5w9qc9ssm6xly74rm34b4a", AuthorManyBi.AUTHOR_MANY_BI, new OrderField[] { AuthorManyBi.AUTHOR_MANY_BI.NAME }, true);
        public static Index BOOK_AUTHOR_FKBO8DRQ2LKNC77OLAJ3KKBJH4 = Internal.createIndex("FKbo8drq2lknc77olaj3kkbjh4", BookAuthor.BOOK_AUTHOR, new OrderField[] { BookAuthor.BOOK_AUTHOR.BOOK_ID }, false);
        public static Index BOOK_AUTHOR_PRIMARY = Internal.createIndex("PRIMARY", BookAuthor.BOOK_AUTHOR, new OrderField[] { BookAuthor.BOOK_AUTHOR.AUTHOR_ID, BookAuthor.BOOK_AUTHOR.BOOK_ID }, true);
        public static Index BOOK_MANYJ_PRIMARY = Internal.createIndex("PRIMARY", BookManyj.BOOK_MANYJ, new OrderField[] { BookManyj.BOOK_MANYJ.ID }, true);
        public static Index BOOK_MANY_BI_PRIMARY = Internal.createIndex("PRIMARY", BookManyBi.BOOK_MANY_BI, new OrderField[] { BookManyBi.BOOK_MANY_BI.ID }, true);
        public static Index BOOK_MANY_BI_AUTHORS_FKA9KDM0F4X1KPV93HJW2E296HE = Internal.createIndex("FKa9kdm0f4x1kpv93hjw2e296he", BookManyBiAuthors.BOOK_MANY_BI_AUTHORS, new OrderField[] { BookManyBiAuthors.BOOK_MANY_BI_AUTHORS.AUTHORS_ID }, false);
        public static Index BOOK_MANY_BI_AUTHORS_PRIMARY = Internal.createIndex("PRIMARY", BookManyBiAuthors.BOOK_MANY_BI_AUTHORS, new OrderField[] { BookManyBiAuthors.BOOK_MANY_BI_AUTHORS.BOOKS_ID, BookManyBiAuthors.BOOK_MANY_BI_AUTHORS.AUTHORS_ID }, true);
        public static Index CHILD1JT_PRIMARY = Internal.createIndex("PRIMARY", Child1jt.CHILD1JT, new OrderField[] { Child1jt.CHILD1JT.ID }, true);
        public static Index CHILD1MS_PRIMARY = Internal.createIndex("PRIMARY", Child1ms.CHILD1MS, new OrderField[] { Child1ms.CHILD1MS.ID }, true);
        public static Index CHILD1TPC_PRIMARY = Internal.createIndex("PRIMARY", Child1tpc.CHILD1TPC, new OrderField[] { Child1tpc.CHILD1TPC.ID }, true);
        public static Index CHILD2JT_PRIMARY = Internal.createIndex("PRIMARY", Child2jt.CHILD2JT, new OrderField[] { Child2jt.CHILD2JT.ID }, true);
        public static Index CHILD2MS_PRIMARY = Internal.createIndex("PRIMARY", Child2ms.CHILD2MS, new OrderField[] { Child2ms.CHILD2MS.ID }, true);
        public static Index CHILD2TPC_PRIMARY = Internal.createIndex("PRIMARY", Child2tpc.CHILD2TPC, new OrderField[] { Child2tpc.CHILD2TPC.ID }, true);
        public static Index HIBERNATE_SEQUENCES_PRIMARY = Internal.createIndex("PRIMARY", HibernateSequences.HIBERNATE_SEQUENCES, new OrderField[] { HibernateSequences.HIBERNATE_SEQUENCES.SEQUENCE_NAME }, true);
        public static Index IDENTITY_GENERATOR_PRIMARY = Internal.createIndex("PRIMARY", IdentityGenerator.IDENTITY_GENERATOR, new OrderField[] { IdentityGenerator.IDENTITY_GENERATOR.ID }, true);
        public static Index PARENTTPC_PRIMARY = Internal.createIndex("PRIMARY", Parenttpc.PARENTTPC, new OrderField[] { Parenttpc.PARENTTPC.ID }, true);
        public static Index PARENT_JT_PRIMARY = Internal.createIndex("PRIMARY", ParentJt.PARENT_JT, new OrderField[] { ParentJt.PARENT_JT.ID }, true);
        public static Index PARENT_ST_PRIMARY = Internal.createIndex("PRIMARY", ParentSt.PARENT_ST, new OrderField[] { ParentSt.PARENT_ST.ID }, true);
        public static Index POOLED_SEQUENCE_GENERATOR_PRIMARY = Internal.createIndex("PRIMARY", PooledSequenceGenerator.POOLED_SEQUENCE_GENERATOR, new OrderField[] { PooledSequenceGenerator.POOLED_SEQUENCE_GENERATOR.ID }, true);
        public static Index POST_COMMENT_MANY_FKIJQORVAAWMHGNKX917PS7MFP9 = Internal.createIndex("FKijqorvaawmhgnkx917ps7mfp9", PostCommentMany.POST_COMMENT_MANY, new OrderField[] { PostCommentMany.POST_COMMENT_MANY.POST_ID }, false);
        public static Index POST_COMMENT_MANY_PRIMARY = Internal.createIndex("PRIMARY", PostCommentMany.POST_COMMENT_MANY, new OrderField[] { PostCommentMany.POST_COMMENT_MANY.ID }, true);
        public static Index POST_COMMENT_MANY_BI_FKQDJUHSGS3OPNLXT26S15U0YQF = Internal.createIndex("FKqdjuhsgs3opnlxt26s15u0yqf", PostCommentManyBi.POST_COMMENT_MANY_BI, new OrderField[] { PostCommentManyBi.POST_COMMENT_MANY_BI.POST_ID }, false);
        public static Index POST_COMMENT_MANY_BI_PRIMARY = Internal.createIndex("PRIMARY", PostCommentManyBi.POST_COMMENT_MANY_BI, new OrderField[] { PostCommentManyBi.POST_COMMENT_MANY_BI.ID }, true);
        public static Index POST_COMMENT_UNI_MANY_FKE4H8SRREB0UVU98PBCCFIUQ16 = Internal.createIndex("FKe4h8srreb0uvu98pbccfiuq16", PostCommentUniMany.POST_COMMENT_UNI_MANY, new OrderField[] { PostCommentUniMany.POST_COMMENT_UNI_MANY.POST_ID1, PostCommentUniMany.POST_COMMENT_UNI_MANY.POST_ID2 }, false);
        public static Index POST_COMMENT_UNI_MANY_PRIMARY = Internal.createIndex("PRIMARY", PostCommentUniMany.POST_COMMENT_UNI_MANY, new OrderField[] { PostCommentUniMany.POST_COMMENT_UNI_MANY.ID }, true);
        public static Index POST_DETAILS_ONE_PRIMARY = Internal.createIndex("PRIMARY", PostDetailsOne.POST_DETAILS_ONE, new OrderField[] { PostDetailsOne.POST_DETAILS_ONE.POST_ID }, true);
        public static Index POST_DETAILS_ONE_BI_PRIMARY = Internal.createIndex("PRIMARY", PostDetailsOneBi.POST_DETAILS_ONE_BI, new OrderField[] { PostDetailsOneBi.POST_DETAILS_ONE_BI.POST_ID }, true);
        public static Index POST_MANY_UNI_PRIMARY = Internal.createIndex("PRIMARY", PostManyUni.POST_MANY_UNI, new OrderField[] { PostManyUni.POST_MANY_UNI.ID }, true);
        public static Index POST_MANY_UNI_TAGS_FKNUXK5IFM2NP8MUXKNV1XOATXL = Internal.createIndex("FKnuxk5ifm2np8muxknv1xoatxl", PostManyUniTags.POST_MANY_UNI_TAGS, new OrderField[] { PostManyUniTags.POST_MANY_UNI_TAGS.TAGS_ID }, false);
        public static Index POST_MANY_UNI_TAGS_PRIMARY = Internal.createIndex("PRIMARY", PostManyUniTags.POST_MANY_UNI_TAGS, new OrderField[] { PostManyUniTags.POST_MANY_UNI_TAGS.POST_MANY_UNI_ID, PostManyUniTags.POST_MANY_UNI_TAGS.TAGS_ID }, true);
        public static Index POST_ONE_PRIMARY = Internal.createIndex("PRIMARY", PostOne.POST_ONE, new OrderField[] { PostOne.POST_ONE.ID }, true);
        public static Index POST_ONE_BI_PRIMARY = Internal.createIndex("PRIMARY", PostOneBi.POST_ONE_BI, new OrderField[] { PostOneBi.POST_ONE_BI.ID }, true);
        public static Index POST_ONE_TO_ONE_PRIMARY = Internal.createIndex("PRIMARY", PostOneToOne.POST_ONE_TO_ONE, new OrderField[] { PostOneToOne.POST_ONE_TO_ONE.ID }, true);
        public static Index POST_ONE_TO_ONE_BI_PRIMARY = Internal.createIndex("PRIMARY", PostOneToOneBi.POST_ONE_TO_ONE_BI, new OrderField[] { PostOneToOneBi.POST_ONE_TO_ONE_BI.ID }, true);
        public static Index POST_ONE_UNI_PRIMARY = Internal.createIndex("PRIMARY", PostOneUni.POST_ONE_UNI, new OrderField[] { PostOneUni.POST_ONE_UNI.ID1, PostOneUni.POST_ONE_UNI.ID2 }, true);
        public static Index POST_WITH_COLLECTION_PRIMARY = Internal.createIndex("PRIMARY", PostWithCollection.POST_WITH_COLLECTION, new OrderField[] { PostWithCollection.POST_WITH_COLLECTION.ID }, true);
        public static Index POST_WITH_COLLECTION_LIST_OF_COMPLEX_FKCYYJ9CLP6U114UCY5D6TX8XH9 = Internal.createIndex("FKcyyj9clp6u114ucy5d6tx8xh9", PostWithCollectionListOfComplex.POST_WITH_COLLECTION_LIST_OF_COMPLEX, new OrderField[] { PostWithCollectionListOfComplex.POST_WITH_COLLECTION_LIST_OF_COMPLEX.POST_WITH_COLLECTION_ID }, false);
        public static Index POST_WITH_COLLECTION_LIST_OF_STRINGS_FKED0FRWO7QVBY7K5GPFRVWUT2I = Internal.createIndex("FKed0frwo7qvby7k5gpfrvwut2i", PostWithCollectionListOfStrings.POST_WITH_COLLECTION_LIST_OF_STRINGS, new OrderField[] { PostWithCollectionListOfStrings.POST_WITH_COLLECTION_LIST_OF_STRINGS.POST_WITH_COLLECTION_ID }, false);
        public static Index SEQUENCE_GENERATOR_PRIMARY = Internal.createIndex("PRIMARY", SequenceGenerator.SEQUENCE_GENERATOR, new OrderField[] { SequenceGenerator.SEQUENCE_GENERATOR.ID }, true);
        public static Index STANDALONE_ENTITY_PRIMARY = Internal.createIndex("PRIMARY", StandaloneEntity.STANDALONE_ENTITY, new OrderField[] { StandaloneEntity.STANDALONE_ENTITY.ID }, true);
        public static Index TABLE_GENERATOR_PRIMARY = Internal.createIndex("PRIMARY", TableGenerator.TABLE_GENERATOR, new OrderField[] { TableGenerator.TABLE_GENERATOR.ID }, true);
        public static Index TAG_MANY_UNI_PRIMARY = Internal.createIndex("PRIMARY", TagManyUni.TAG_MANY_UNI, new OrderField[] { TagManyUni.TAG_MANY_UNI.ID }, true);
        public static Index UUIDGENERATOR_PRIMARY = Internal.createIndex("PRIMARY", Uuidgenerator.UUIDGENERATOR, new OrderField[] { Uuidgenerator.UUIDGENERATOR.ID }, true);
    }
}
