/*
 * This file is generated by jOOQ.
 */
package me.vukas.jooq.db;


import javax.annotation.Generated;

import me.vukas.jooq.db.tables.Assigneduuidgenerator;
import me.vukas.jooq.db.tables.AuthorManyBi;
import me.vukas.jooq.db.tables.AuthorManyj;
import me.vukas.jooq.db.tables.BookAuthor;
import me.vukas.jooq.db.tables.BookManyBi;
import me.vukas.jooq.db.tables.BookManyBiAuthors;
import me.vukas.jooq.db.tables.BookManyj;
import me.vukas.jooq.db.tables.Child1jt;
import me.vukas.jooq.db.tables.Child1ms;
import me.vukas.jooq.db.tables.Child1tpc;
import me.vukas.jooq.db.tables.Child2jt;
import me.vukas.jooq.db.tables.Child2ms;
import me.vukas.jooq.db.tables.Child2tpc;
import me.vukas.jooq.db.tables.HibernateSequence;
import me.vukas.jooq.db.tables.HibernateSequences;
import me.vukas.jooq.db.tables.IdentityGenerator;
import me.vukas.jooq.db.tables.ParentJt;
import me.vukas.jooq.db.tables.ParentSt;
import me.vukas.jooq.db.tables.Parenttpc;
import me.vukas.jooq.db.tables.PooledSequence;
import me.vukas.jooq.db.tables.PooledSequenceGenerator;
import me.vukas.jooq.db.tables.PostCommentMany;
import me.vukas.jooq.db.tables.PostCommentManyBi;
import me.vukas.jooq.db.tables.PostCommentUniMany;
import me.vukas.jooq.db.tables.PostDetailsOne;
import me.vukas.jooq.db.tables.PostDetailsOneBi;
import me.vukas.jooq.db.tables.PostManyUni;
import me.vukas.jooq.db.tables.PostManyUniTags;
import me.vukas.jooq.db.tables.PostOne;
import me.vukas.jooq.db.tables.PostOneBi;
import me.vukas.jooq.db.tables.PostOneToOne;
import me.vukas.jooq.db.tables.PostOneToOneBi;
import me.vukas.jooq.db.tables.PostOneUni;
import me.vukas.jooq.db.tables.PostWithCollection;
import me.vukas.jooq.db.tables.PostWithCollectionListOfComplex;
import me.vukas.jooq.db.tables.PostWithCollectionListOfStrings;
import me.vukas.jooq.db.tables.SequenceGenerator;
import me.vukas.jooq.db.tables.StandaloneEntity;
import me.vukas.jooq.db.tables.TableGenerator;
import me.vukas.jooq.db.tables.TagManyUni;
import me.vukas.jooq.db.tables.Uuidgenerator;


/**
 * Convenience access to all tables in hi_perf_java_pers
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>hi_perf_java_pers.assigneduuidgenerator</code>.
     */
    public static final Assigneduuidgenerator ASSIGNEDUUIDGENERATOR = me.vukas.jooq.db.tables.Assigneduuidgenerator.ASSIGNEDUUIDGENERATOR;

    /**
     * The table <code>hi_perf_java_pers.author_manyj</code>.
     */
    public static final AuthorManyj AUTHOR_MANYJ = me.vukas.jooq.db.tables.AuthorManyj.AUTHOR_MANYJ;

    /**
     * The table <code>hi_perf_java_pers.author_many_bi</code>.
     */
    public static final AuthorManyBi AUTHOR_MANY_BI = me.vukas.jooq.db.tables.AuthorManyBi.AUTHOR_MANY_BI;

    /**
     * The table <code>hi_perf_java_pers.book_author</code>.
     */
    public static final BookAuthor BOOK_AUTHOR = me.vukas.jooq.db.tables.BookAuthor.BOOK_AUTHOR;

    /**
     * The table <code>hi_perf_java_pers.book_manyj</code>.
     */
    public static final BookManyj BOOK_MANYJ = me.vukas.jooq.db.tables.BookManyj.BOOK_MANYJ;

    /**
     * The table <code>hi_perf_java_pers.book_many_bi</code>.
     */
    public static final BookManyBi BOOK_MANY_BI = me.vukas.jooq.db.tables.BookManyBi.BOOK_MANY_BI;

    /**
     * The table <code>hi_perf_java_pers.book_many_bi_authors</code>.
     */
    public static final BookManyBiAuthors BOOK_MANY_BI_AUTHORS = me.vukas.jooq.db.tables.BookManyBiAuthors.BOOK_MANY_BI_AUTHORS;

    /**
     * The table <code>hi_perf_java_pers.child1jt</code>.
     */
    public static final Child1jt CHILD1JT = me.vukas.jooq.db.tables.Child1jt.CHILD1JT;

    /**
     * The table <code>hi_perf_java_pers.child1ms</code>.
     */
    public static final Child1ms CHILD1MS = me.vukas.jooq.db.tables.Child1ms.CHILD1MS;

    /**
     * The table <code>hi_perf_java_pers.child1tpc</code>.
     */
    public static final Child1tpc CHILD1TPC = me.vukas.jooq.db.tables.Child1tpc.CHILD1TPC;

    /**
     * The table <code>hi_perf_java_pers.child2jt</code>.
     */
    public static final Child2jt CHILD2JT = me.vukas.jooq.db.tables.Child2jt.CHILD2JT;

    /**
     * The table <code>hi_perf_java_pers.child2ms</code>.
     */
    public static final Child2ms CHILD2MS = me.vukas.jooq.db.tables.Child2ms.CHILD2MS;

    /**
     * The table <code>hi_perf_java_pers.child2tpc</code>.
     */
    public static final Child2tpc CHILD2TPC = me.vukas.jooq.db.tables.Child2tpc.CHILD2TPC;

    /**
     * The table <code>hi_perf_java_pers.hibernate_sequence</code>.
     */
    public static final HibernateSequence HIBERNATE_SEQUENCE = me.vukas.jooq.db.tables.HibernateSequence.HIBERNATE_SEQUENCE;

    /**
     * The table <code>hi_perf_java_pers.hibernate_sequences</code>.
     */
    public static final HibernateSequences HIBERNATE_SEQUENCES = me.vukas.jooq.db.tables.HibernateSequences.HIBERNATE_SEQUENCES;

    /**
     * The table <code>hi_perf_java_pers.identity_generator</code>.
     */
    public static final IdentityGenerator IDENTITY_GENERATOR = me.vukas.jooq.db.tables.IdentityGenerator.IDENTITY_GENERATOR;

    /**
     * The table <code>hi_perf_java_pers.parenttpc</code>.
     */
    public static final Parenttpc PARENTTPC = me.vukas.jooq.db.tables.Parenttpc.PARENTTPC;

    /**
     * The table <code>hi_perf_java_pers.parent_jt</code>.
     */
    public static final ParentJt PARENT_JT = me.vukas.jooq.db.tables.ParentJt.PARENT_JT;

    /**
     * The table <code>hi_perf_java_pers.parent_st</code>.
     */
    public static final ParentSt PARENT_ST = me.vukas.jooq.db.tables.ParentSt.PARENT_ST;

    /**
     * The table <code>hi_perf_java_pers.pooled_sequence</code>.
     */
    public static final PooledSequence POOLED_SEQUENCE = me.vukas.jooq.db.tables.PooledSequence.POOLED_SEQUENCE;

    /**
     * The table <code>hi_perf_java_pers.pooled_sequence_generator</code>.
     */
    public static final PooledSequenceGenerator POOLED_SEQUENCE_GENERATOR = me.vukas.jooq.db.tables.PooledSequenceGenerator.POOLED_SEQUENCE_GENERATOR;

    /**
     * The table <code>hi_perf_java_pers.post_comment_many</code>.
     */
    public static final PostCommentMany POST_COMMENT_MANY = me.vukas.jooq.db.tables.PostCommentMany.POST_COMMENT_MANY;

    /**
     * The table <code>hi_perf_java_pers.post_comment_many_bi</code>.
     */
    public static final PostCommentManyBi POST_COMMENT_MANY_BI = me.vukas.jooq.db.tables.PostCommentManyBi.POST_COMMENT_MANY_BI;

    /**
     * The table <code>hi_perf_java_pers.post_comment_uni_many</code>.
     */
    public static final PostCommentUniMany POST_COMMENT_UNI_MANY = me.vukas.jooq.db.tables.PostCommentUniMany.POST_COMMENT_UNI_MANY;

    /**
     * The table <code>hi_perf_java_pers.post_details_one</code>.
     */
    public static final PostDetailsOne POST_DETAILS_ONE = me.vukas.jooq.db.tables.PostDetailsOne.POST_DETAILS_ONE;

    /**
     * The table <code>hi_perf_java_pers.post_details_one_bi</code>.
     */
    public static final PostDetailsOneBi POST_DETAILS_ONE_BI = me.vukas.jooq.db.tables.PostDetailsOneBi.POST_DETAILS_ONE_BI;

    /**
     * The table <code>hi_perf_java_pers.post_many_uni</code>.
     */
    public static final PostManyUni POST_MANY_UNI = me.vukas.jooq.db.tables.PostManyUni.POST_MANY_UNI;

    /**
     * The table <code>hi_perf_java_pers.post_many_uni_tags</code>.
     */
    public static final PostManyUniTags POST_MANY_UNI_TAGS = me.vukas.jooq.db.tables.PostManyUniTags.POST_MANY_UNI_TAGS;

    /**
     * The table <code>hi_perf_java_pers.post_one</code>.
     */
    public static final PostOne POST_ONE = me.vukas.jooq.db.tables.PostOne.POST_ONE;

    /**
     * The table <code>hi_perf_java_pers.post_one_bi</code>.
     */
    public static final PostOneBi POST_ONE_BI = me.vukas.jooq.db.tables.PostOneBi.POST_ONE_BI;

    /**
     * The table <code>hi_perf_java_pers.post_one_to_one</code>.
     */
    public static final PostOneToOne POST_ONE_TO_ONE = me.vukas.jooq.db.tables.PostOneToOne.POST_ONE_TO_ONE;

    /**
     * The table <code>hi_perf_java_pers.post_one_to_one_bi</code>.
     */
    public static final PostOneToOneBi POST_ONE_TO_ONE_BI = me.vukas.jooq.db.tables.PostOneToOneBi.POST_ONE_TO_ONE_BI;

    /**
     * The table <code>hi_perf_java_pers.post_one_uni</code>.
     */
    public static final PostOneUni POST_ONE_UNI = me.vukas.jooq.db.tables.PostOneUni.POST_ONE_UNI;

    /**
     * The table <code>hi_perf_java_pers.post_with_collection</code>.
     */
    public static final PostWithCollection POST_WITH_COLLECTION = me.vukas.jooq.db.tables.PostWithCollection.POST_WITH_COLLECTION;

    /**
     * The table <code>hi_perf_java_pers.post_with_collection_list_of_complex</code>.
     */
    public static final PostWithCollectionListOfComplex POST_WITH_COLLECTION_LIST_OF_COMPLEX = me.vukas.jooq.db.tables.PostWithCollectionListOfComplex.POST_WITH_COLLECTION_LIST_OF_COMPLEX;

    /**
     * The table <code>hi_perf_java_pers.post_with_collection_list_of_strings</code>.
     */
    public static final PostWithCollectionListOfStrings POST_WITH_COLLECTION_LIST_OF_STRINGS = me.vukas.jooq.db.tables.PostWithCollectionListOfStrings.POST_WITH_COLLECTION_LIST_OF_STRINGS;

    /**
     * The table <code>hi_perf_java_pers.sequence_generator</code>.
     */
    public static final SequenceGenerator SEQUENCE_GENERATOR = me.vukas.jooq.db.tables.SequenceGenerator.SEQUENCE_GENERATOR;

    /**
     * The table <code>hi_perf_java_pers.standalone_entity</code>.
     */
    public static final StandaloneEntity STANDALONE_ENTITY = me.vukas.jooq.db.tables.StandaloneEntity.STANDALONE_ENTITY;

    /**
     * The table <code>hi_perf_java_pers.table_generator</code>.
     */
    public static final TableGenerator TABLE_GENERATOR = me.vukas.jooq.db.tables.TableGenerator.TABLE_GENERATOR;

    /**
     * The table <code>hi_perf_java_pers.tag_many_uni</code>.
     */
    public static final TagManyUni TAG_MANY_UNI = me.vukas.jooq.db.tables.TagManyUni.TAG_MANY_UNI;

    /**
     * The table <code>hi_perf_java_pers.uuidgenerator</code>.
     */
    public static final Uuidgenerator UUIDGENERATOR = me.vukas.jooq.db.tables.Uuidgenerator.UUIDGENERATOR;
}
